### ISSUE TITLE
auto assign in for loops

### ISSUE THREAD

**Issue by Sanegv** [Eclalang/Ecla#120]
the following code:
```ecla
for(i := 1; i < 4; i++){
    ...
}
```
returns an error `Expected variable name instead of :`

while this code:
```ecla
for(var i int = 1; i < 4; i++){
    ...
}
```
is still valid.

**Comment by mkarten** [comment]
you code is not correct you need to use commas instead of semicolon

this for loop is correct :
```ecla
for(a := 1, i < 4, i++){
    ...
}
```

but there is still a bug with the initial variable declaration that is under investigation

**Comment by mkarten** [comment]
your code does not work since the semicolons need to be replaced by commas

this will be a valid ecla for loop:
```ecla
for(var i int = 1, i < 4, i++){
    ...
}
```
-
