### ISSUE TITLE
int_min*int_min == 0 currently

### ISSUE THREAD

**Issue by Llelepipede** [Eclalang/Ecla#13]

**Comment by tot0p** [comment]
Please share the code in your issue @Llelepipede

**Comment by Llelepipede** [comment]
`import "console";

function fonction(a: int) (int){
    console.println("a: "+a);
    if (a >= 0) {
        return fonction(a+a)*a;
    }
    console.println(a+" * "+a+ " = "+a*a);
    return a*a;
}

console.println("fin: " +fonction(1));
`

**Comment by Llelepipede** [comment]
```import "console";

function fonction(a: int) (int){
    console.println("a: "+a);
    if (a >= 0) {
        return fonction(a+a)*a;
    }
    console.println(a+" * "+a+ " = "+a*a);
    return a*a;
}

console.println("fin: " +fonction(1));
```

**Comment by mkarten** [comment]
The behaviour of int_min*int_min == 0 is expected and is valid for ecla
