### ISSUE TITLE
Proofreading of the documentation

### ISSUE THREAD

**Issue by Delphine-Alex** [Eclalang/Ecla#183]
We urgently need to correct spelling mistakes in French, there are more than 30 of them in all Ecla documentation!

You can see an example here:

<img width="1091" alt="Capture d’écran 2024-01-28 à 16 39 25" src="https://github.com/Eclalang/Ecla/assets/70972077/63eb221c-1450-4bf5-89dc-7ab8e44e4aa0">
<img width="1097" alt="Capture d’écran 2024-01-28 à 16 37 19" src="https://github.com/Eclalang/Ecla/assets/70972077/7cdd4b12-ae4a-4adb-846c-7bba60e5c5cf">

**Comment by mkarten** [comment]
We already have issue #170 opened to list all spelling/wording errors
Can you transfer over your comment and example ?
