### ISSUE TITLE
Structure markdown

### ISSUE THREAD

**Issue by Delphine-Alex** [Eclalang/Ecla#63]
Have the same file structure (respecting uppercase and lowercase letters, handling tags and styles, _etc._) in markdown to display documentation with React. High priority on the folders [docs](https://github.com/Eclalang/Ecla/tree/main/docs) and all its contents, [INSTALL](https://github.com/Eclalang/Ecla/blob/main/INSTALL.md), [README](https://github.com/Eclalang/Ecla/blob/main/README.md) and [Grammar](https://github.com/Eclalang/Ecla/blob/main/parser/Grammar.md).

**Comment by tot0p** [comment]
In [time.md](https://github.com/Eclalang/Ecla/blob/main/docs/Libraries/time.md), there are two h1 instead of one.
